version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run:
          command: linting
          name: npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-{{ checksum "package.json" }}
      - run:
          name: installng local dependencies
          command: npm run lint
      - run:
          name: building
          command: npm run build

  deploy:
    docker:
      - image: circleci/node:10.14.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run:
          name: clean functions ssr directory
          command: npm run functions:ssr:clean
      - run:
          name: copy dist directory to function
          command: npm run build:copy
      - run:
          name: firebase deploy
          command: |
            project_id=$DEV_PROJECT_ID
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              project_id=$PROJECT_ID
            fi

            ./scripts/deploy-firebase.sh -p $project_id -t $FIREBASE_TOKEN

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
